apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: 058264537240.dkr.ecr.eu-central-1.amazonaws.com/hello-app
    newTag: e2b67819cfc2b3a56c2bed789ea316fe9a16053e
